### ISSUE TITLE
Can POSQ use with car-like robot?

### ISSUE THREAD

**Issue by dajk9x** [palmieri/posq#2]
Hi,
I read your paper and source code, but I don't find anything mentioning the minimum turn radius, which is the difference of car-like robot and wheel robot.
So my question is can POSQ use with car-like robot? and if yes, how to to it. 

Thank you

**Comment by palmieri** [comment]
Hi, 

POSQ is limited to unicycle (differential-drive) kinematics. 

Best, 
L.
